import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { verifyTor } from "../actions";
import StatusBadge from "@/components/StatusBadge";
import DocumentUploader from "@/components/DocumentUploader";
import DeleteTorAdminButton from "@/components/DeleteTorAdminButton";
export default async function AdminTorDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const { data: tor } = await supabase.from("budget_tors").select("*, faculties(name)").eq("id", id).single(); if (!tor) notFound();
  const [{ data: documents }, { data: history }] = await Promise.all([supabase.from("budget_documents").select("*").eq("entity_type", "tor").eq("entity_id", id), supabase.from("budget_history").select("*").eq("entity_type", "tor").eq("entity_id", id).order("created_at", { ascending: true })]);
  const canReview = ["Diajukan", "Diverifikasi"].includes(tor.status);
  async function approve(fd: FormData) { "use server"; await verifyTor(id, "Disetujui", (fd.get("note") as string) || "Disetujui."); }
  async function reject(fd: FormData) { "use server"; await verifyTor(id, "Ditolak", (fd.get("note") as string) || "TOR ditolak."); }
  async function fix(fd: FormData) { "use server"; await verifyTor(id, "Perlu Perbaikan", (fd.get("note") as string) || "Mohon lakukan perbaikan."); }
  const details = [["Program", tor.program], ["Kegiatan", tor.kegiatan], ["Sumber Dana", tor.sumber_dana], ["Tujuan", tor.tujuan], ["Output", tor.output], ["Outcome", tor.outcome], ["Lokasi", tor.lokasi], ["Waktu Pelaksanaan", tor.waktu_pelaksanaan], ["Rincian Anggaran", tor.rincian_anggaran]];
  return <div className="max-w-3xl"><div className="flex items-start justify-between"><div><h1 className="text-xl font-bold">{tor.number}</h1><p className="mt-1 text-lg">{tor.judul}</p><p className="text-sm text-[#5B5A55]">{tor.faculties?.name ?? "—"}</p><div className="my-3"><StatusBadge status={tor.status} /></div></div><DeleteTorAdminButton id={id} /></div><div className="grid gap-3 rounded-lg border border-[#E1DDCF] bg-white p-4 text-sm sm:grid-cols-2">{details.map(([label, val]) => <div key={label}><div className="text-xs text-[#5B5A55]">{label}</div><div className="whitespace-pre-line font-semibold">{val || "—"}</div></div>)}<div className="sm:col-span-2"><div className="text-xs text-[#5B5A55]">Latar Belakang</div><div className="whitespace-pre-line">{tor.latar_belakang}</div></div></div>{tor.catatan_verifikator && <div className="my-4 rounded-md bg-orange-50 p-3 text-sm text-orange-700"><strong>Catatan Verifikator:</strong> {tor.catatan_verifikator}</div>}<div className="my-4 rounded-lg border border-[#E1DDCF] bg-white p-4"><div className="mb-2 font-semibold text-sm">Riwayat</div>{history?.map((h) => <div key={h.id} className="mb-1 text-xs text-[#5B5A55]">{new Date(h.created_at).toLocaleDateString("id-ID")} — {h.event}</div>)}</div><DocumentUploader entityType="tor" entityId={id} facultyId={tor.faculty_id} documents={documents ?? []} editable={canReview} />{canReview && <form className="flex flex-col gap-3 rounded-lg border border-[#E1DDCF] bg-white p-4"><textarea name="note" placeholder="Catatan verifikator" className="min-h-[70px] rounded-md border border-[#E1DDCF] p-2 text-sm" /><div className="flex gap-2"><button formAction={approve} className="rounded-md bg-green-700 px-4 py-2 text-sm text-white">Setujui</button><button formAction={fix} className="rounded-md bg-amber-600 px-4 py-2 text-sm text-white">Perlu Perbaikan</button><button formAction={reject} className="rounded-md bg-red-600 px-4 py-2 text-sm text-white">Tolak</button></div></form>}</div>;
}
