import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import StatusBadge from "@/components/StatusBadge";
import TableActionLink from "@/components/TableActionLink";
type TorRow = { id: string; number: string; judul: string; status: string; faculties: { name: string } | null };
export default async function AdminTorPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status } = await searchParams; const supabase = await createClient();
  let query = supabase.from("budget_tors").select("*, faculties(name)").order("created_at", { ascending: true }); if (status) query = query.eq("status", status);
  const { data } = await query; const statuses = ["Draft", "Diajukan", "Diverifikasi", "Disetujui", "Ditolak", "Perlu Perbaikan"];
  return <div className="mx-auto flex max-w-7xl flex-col gap-5"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#0B5B35]">Pengajuan</p><h1 className="mt-1 text-2xl font-bold">TOR</h1><p className="mt-2 text-sm text-[#64736A]">Kelola dan tinjau TOR dari seluruh fakultas/unit.</p></div><div className="flex gap-2 overflow-x-auto pb-1"><Link href="/admin/tor" className={`whitespace-nowrap rounded-full border px-3.5 py-2 text-xs font-semibold ${!status ? "border-[#0B5B35] bg-[#0B5B35] text-white" : "bg-white text-[#64736A]"}`}>Semua</Link>{statuses.map((s) => <Link key={s} href={`/admin/tor?status=${encodeURIComponent(s)}`} className={`whitespace-nowrap rounded-full border px-3.5 py-2 text-xs font-semibold ${status === s ? "border-[#0B5B35] bg-[#0B5B35] text-white" : "bg-white text-[#64736A]"}`}>{s}</Link>)}</div>
    <div className="overflow-hidden rounded-2xl border border-[#DCE6DF] bg-white shadow-sm"><table className="w-full text-sm"><thead className="border-b bg-[#F5F8F5] text-left text-xs uppercase text-[#64736A]"><tr><th className="px-4 py-3">No. TOR</th><th className="px-4 py-3">Fakultas</th><th className="px-4 py-3">Judul</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody>{(data as TorRow[] | null)?.map((tor) => <tr key={tor.id} className="border-b border-[#EDF2EE]"><td className="px-4 py-4 font-bold text-[#0B5B35]">{tor.number}</td><td className="px-4 py-4">{tor.faculties?.name ?? "—"}</td><td className="px-4 py-4 font-semibold">{tor.judul}</td><td className="px-4 py-4"><StatusBadge status={tor.status} /></td><td className="px-4 py-4"><TableActionLink href={`/admin/tor/${tor.id}`} /></td></tr>)}{!data?.length && <tr><td colSpan={5} className="px-4 py-12 text-center text-[#64736A]">Tidak ada data.</td></tr>}</tbody></table></div>
  </div>;
}
